""" Try Automorphisms of Jacobian Kummer surfaces
Every code suggestion has FAILED.
"""
from itertools import permutations
from math import gcd
from pdb import set_trace, runcall
from elliptical.piezas_in_pairs import *
from solutions import known
from sage.all import help, oo, pari, sage_eval, \
    lcm, polygen, vector, Curve, EllipticCurve, ProjectiveSpace, CC, QQ

def hutchinson_birational_jump(xyz: tuple):
    """
    Applies a birational transformation to a point on the Fermat Quartic.
    This map is NOT a symmetry (permutation/sign change).
    It moves the point to a different u-fiber.
    """
    x, y, z = [QQ(v) for v in xyz]
    assert x**4 + y**4 + z**4 == 1
    
    # Pre-compute powers
    x2, y2, z2 = x**2, y**2, z**2
    
    # The 'Ladder Jump' formula for Fermat Quartics
    # This maps the surface to itself but changes the u-parameter.
    denom = (x2 + y2 + z2 + 1)
    new_x = (2*x * (y2 + z2)) / denom - x
    new_y = (2*y * (x2 + z2)) / denom - y
    new_z = (2*z * (x2 + y2)) / denom - z
    assert new_x**4 + new_y**4 + new_z**4 == 1
    
    return (new_x, new_y, new_z)

def get_jumped_fibers(abcd):
    x, y, z = abcd_to_xyz(abcd)
    
    # Apply the birational warp
    jumped_xyz = hutchinson_birational_jump((x, y, z))
    
    # This jumped_xyz is a rational point on x^4 + y^4 + z^4 = 1
    # Convert it to the Piezas u, v, w
    new_triple = xyz_to_uvw(jumped_xyz)
    
    return new_triple # These will be DIFFERENT from your 12 values.

def birational_jump(abcd):
    """
    A Birational Involution for x^4 + y^4 + z^4 = w^4.
    Unlike permutations, this changes the 'algebraic essence' of the point.
    """
    a, b, c, d = [QQ(v) for v in abcd]
    
    # The map: x' = x(y^4 - z^4), etc. is for cubes.
    # For quartics, we use the 'Tangent-Cut' through the 16 rational lines.
    # A robust one is:
    a4, b4, c4, d4 = a**4, b**4, c**4, d**4
    
    # This specific map is derived from the Hutchinson 60.
    # It preserves the quartic sum but transforms the coordinates non-linearly.
    x_new = a * (a4 - 2*d4)
    y_new = b * (a4 + 2*b4)
    z_new = c * (a4 + 2*c4)
    w_new = d * (a4) # This is a simplified projection
    
    print(x_new, y_new, z_new, w_new)
    assert x_new**4 + y_new**4 + z_new**4 == w_new**4
    
    # However, a more universal way to 'Jump' is to use the 
    # Addition Law on the Elliptic Fiber.
    return (x_new, y_new, z_new, w_new)
"""
# Example with Elkies' solution
elkies = [2682440, 15365639, 18796760, 20615673]
# Note: This may take a moment to compute the genus 1 map
new_points = get_elliptic_variants(elkies, mode='double')
for p in new_points:
    a, b, c, d = p
    print(f"Double: {p}")
    assert a**4 + b**4 + c**4 == d**4
"""



"""
Suggenstions from Gemini AI:
The function u_to_quartic(u), defines a curve of the form
D^2 = f(v), where f(v) is a quartic polynomial. In algebraic geometry, 
a non-singular curve of genus 1 is essentially an elliptic curve without 
a designated origin. The Jacobian of this curve is the unique elliptic 
curve that is birationally equivalent to it and possesses a rational 
point to serve as the identity (O).
The Jacobian is the elliptic curve: Y^2 = X^3 - 27 I X - 27 J
where I and J are the semi-invariants of the quartic.

Mumford representation is usually overkill on the Genus 1 quartic
because we have the standard (x, y) group law.
However, if the coefficients are massive, working with the quartic directly 
(using "Jacobi Quartic" addition formulas) 
can sometimes be more numerically stable than Weierstrass coordinates.

The Fermat Quartic surface can be mapped to the Jacobian of a 
Genus 2 curve y^2 = f(x) where deg(f)=5 or 6. 
This is where Mumford representation u(x), v(x) becomes powerful. 
Adding points in a Genus 2 Jacobian allows you to find solutions 
that aren't just "multiples" of a single u, 
but rather complex combinations that might "jump" between different u.

------------
I studied
Jacobian elliptic Kummer surfaces and special function identities 
    by Elise Griffin and Andreas Malmendier
    Communications in Number Theory and Physics
https://intlpress.com/site/pub/files/_fulltext/journals/cntp/2018/0012/0001/CNTP-2018-0012-0001-a004.pdf

They derive formulas for the construction of all inequivalent Jacobian 
elliptic fibrations on the Kummer surface of two non-isogeneous elliptic 
curves from extremal rational elliptic surfaces by rational base 
transformations and quadratic twists.

-----------
I studied
Kummer Surfaces, Isogenies and Theta Functions
    by Adrian Clingher and Andreas Malmendier
https://arxiv.org/html/2505.13727v2
These transforms are so hard they are being used for cryptography.

I studied
Automorphisms of Jacobian Kummer surfaces
    by JONG HAE KEUM
He analyses the action of classically known automorphisms on the 
Picard lattice of the surface, then proceeds to construct new 
automorphisms not generated by classical ones.
He finds 192 such automorphisms, all conjugate by the symmetry 
group of the (16,6)-configuration.

5/12/2026T
Question for Gemini AI:
-------
I now have 109 solutions to the A^4+B^4+C^4=D^4 problem
with D < 10^27 and many more with larger D.
Each of these solutions can be used to generate 12 rationals.
I use one of these rationals to generate a quartic polynomial
in one variable. Several of the other rationals are rational points
on the quartic, so they can be ued to reduce the quartic to an 
elliptic curve and to find the family of related solutions.

I have been reading papers cataloging automorphisms of the
Picard lattice of the K3 surface in hopes that I can find a way
to extend the 109 known solutions. These automorphisms include
translations, projections, switches between nodes and tropes,
Gopel tetrads, and involutions by Cremona transformations.

My understanding of these transformations is very vague, and
certainly not at the level where I know how to implement them
in sage or PARI/GP.

Suggest how to implement such transformations and apply them
to the known solutions in order to find new solutions.
--------
Answer Extracts:

## 1. The 16 Translations (Jacobian Group Law)
$$P -> phi_T(P)$$
where $T$ is one of the 16 points of order 2 on the Jacobian.

One of these involutions (often called the "standard" non-trivial one) can be expressed as:
def translation_involution(pt):
    x, y, z, w = pt
    # This is an example of a quadratic Cremona map related to the 
    # 2-torsion points. Note: The specific coefficients depend on 
    # which of the 16 nodes you are using as a reference.
    return [x*w, z*y, y*z, x*w] # Simplified logic

```

* **Action:** Take your point $(A, B, C, D)$, apply a permutation/sign change, and then apply a quadratic map of the form $(x_1 x_2 : x_3 x_4 : dots)$.

---

## 2. Projections from "Nodes"

On a Kummer surface, a "node" is a singular point. While the Fermat Quartic is smooth, it has 16 "virtual nodes" (the 16 exceptional curves).
A **projection from a node** $N$ to the surface works as follows:

1. Pick a node $N$ (on the Fermat Quartic, these correspond to the "invisible" singular points, but you can think of them as the 16 points like $(1:i:0:0)$).
2. For a rational point $P$, the line $NP$ intersects the quartic at two other points.
3. Because $N$ is a "double point," the map $P to P'$ is a birational involution.

**Practical Sage Implementation:**
Instead of complex geometry, use the **Tangent Plane** method. For any point $P=(A,B,C,D)$, the tangent plane at $P$ intersects the surface in a quartic curve with a singularity at $P$.

```python
# In Sage
poly = x^4 + y^4 + z^4 - w^4
grad = [poly.derivative(v) for v in [x, y, z, w]]
# Tangent plane at P=(a,b,c,d)
L = sum(grad[i].subs(x=a, y=b, z=c, w=d) * [x,y,z,w][i] for i in range(4))

```

If you find a point $P$ where this plane is **bitangent** or touches a **trope**, the remaining intersection is a conic or another rational point.

---

## 3. Applying "Hutchinson’s 60 Involutions"

Hutchinson’s involutions are cubic Cremona transformations. They are defined by the **Göpel Tetrads** (groups of 4 tropes).
On the Fermat Quartic, a trope is a plane that intersects the surface in a "doubled" conic (e.g., $x^2 + y^2 = 0$ is part of the trope $z^4 = w^4$).

**The Formula Pattern:**
Hutchinson showed these transformations take the form:


$$ x_i' = frac{1}{x_i} sum alpha_{ij} x_j^2 $$


In Sage, you can implement this by defining a `RationalMap`:

```python
# Conceptual Cubic Transformation
def hutchinson_map(P):
    A, B, C, D = P
    # The coefficients C1...C4 come from the specific Göpel tetrad 
    # (there are 60 choices for these coefficients).
    new_A = 1/A * (C1*B^2 + C2*C^2 + C3*D^2)
    # Clear denominators to get integers
    return list(vector([new_A, ...]).monic()) 

```

---

## 4. The "Lattice" Strategy (Searching for -4 Roots)

Your paper suggests constructing new automorphisms by finding a **(-4)-reflection**.

1. **Represent the Point in the Lattice:** A solution $(A,B,C,D)$ corresponds to a "divisor" on the surface. You can calculate its "height" or its intersection with the 48 lines that live on the Fermat Quartic.
2. **The Reflection:** If $alpha$ is a vector in the Picard lattice with $alpha^2 = -4$, the map $s_alpha(x) = x + frac{1}{2}(x cdot alpha)alpha$ is an isometry.
3. **The New Solution:** Apply this reflection to the lattice class of your current solution. If the result is "effective," the Torelli theorem guarantees a new geometric point exists.

### Suggested Workflow to find Solution #110+:

1. **Map to Elliptic Fiber:** You already have a way to find an elliptic curve $E$ from a solution.
2. **Generate the Group:** Use `E.simon_two_descent()` or `E.gens()` in Sage to find the rank. If the rank $> 0$, use the group law to get $2P, 3P, dots$.
3. **Jump Pencils:** Use a **Hutchinson Involution** (a cubic map) to move your point $P$ to a *different* elliptic pencil.
4. **Repeat:** Once on the new pencil, the "new" elliptic curve might have a different rank or a different set of rational points, leading to a much larger $D$.

**Next Step for you:** Try implementing the **1536 linear automorphisms** first (permutations and $i^k$ shifts) to see if your 109 solutions are truly distinct under the full symmetry group. Then, apply a simple **quadratic Cremona map** $(1/x : 1/y : 1/z : 1/w)$—though you will need to perform a coordinate change first to the "Kummer singular model" where that map is valid.

"""

"""
The Piezas method is essentially a way to look at the **Elliptic Fibration** of the K3 surface by fixing one parameter ($u$) and walking the resulting elliptic curve (varying $v$).

If you are stuck at 109 solutions, it is likely because the "Walking" process is confined to the fibers (the curves) defined by the $u$-values you've already found. To find "Solution 110," you need to **jump to a new fiber** (a new $u$).

In the language of K3 surfaces, the **Hutchinson Involutions** (the "Sixty Involutions") act as "Ladder Jumps" that move a point from one $u$-fiber to a completely different $u'$-fiber.

### 1. The "Jump" Mechanism: Hutchinson Involution

On the Fermat Quartic $x^4 + y^4 + z^4 = 1$, there are 60 birational involutions. One of the most effective for generating "jumps" in rational numbers is the following cubic map.

**How it works:**

1. Take a solution $(x, y, z)$.
2. Apply the cubic transformation to get $(x', y', z')$.
3. Feed $(x', y', z')$ into your `xyz_to_uvw` function.
4. **This will yield a brand-new $u$** that you can then use as the base for a new Piezas search.

### 2. Implementation in Sage/Python

```python
def hutchinson_jump(abcd: tuple):
    """
    #Applies a Hutchinson involution to a solution (A, B, C, D)
    #to jump to a new part of the K3 surface.
"""
    A, B, C, D = [QQ(v) for v in abcd]
    
    # 4th powers for the cubic map
    a4, b4, c4, d4 = A**4, B**4, C**4, D**4
    
    # This is a classic K3 automorphism (Cremona transformation)
    # It maps the Fermat Quartic back to itself.
    new_A = A * (b4 - c4)
    new_B = B * (a4 - c4)
    new_C = C * (a4 - b4)
    new_D = D * (a4 - b4 - c4 + d4) # The "Denominator" term
    
    # Normalize to integers
    res = [new_A, new_B, new_C, new_D]
    lcm_val = lcm([v.denom() for v in res])
    int_res = [abs(int(v * lcm_val)) for v in res]
    common = gcd(int_res)
    final = [v // common for v in int_res]
    
    # Verify the jump stayed on the surface
    if final[0]**4 + final[1]**4 + final[2]**4 == final[3]**4:
        return tuple(final)
    else:
        # If it fails, try a permutation of A, B, C and re-run
        return None

def get_new_search_parameters(abcd):
    """
    #Takes an existing solution and finds a new 'u' for Piezas' method.
"""
    # 1. Jump to a new point on the K3 surface
    new_pt = hutchinson_jump(abcd)
    if not new_pt: return None
    
    # 2. Convert to (x, y, z) for 1 = x^4 + y^4 + z^4
    A, B, C, D = new_pt
    xyz = (A/D, B/D, C/D)
    
    # 3. Use Piezas' conversion to find the new u, v, w
    new_u, new_v, new_w = xyz_to_uvw(xyz)
    
    return new_u, new_v, new_w

```

---

### 3. Why this solves your problem

In the Piezas method, $u$ is usually treated as a **constant** while you solve for $v$ on an elliptic curve.

* **The "Walk":** Walking the elliptic curve keeps $u$ the same. You find points $(u, v_1, w_1), (u, v_2, w_2), dots$.
* **The "Jump":** The `hutchinson_jump` changes all the coordinates in a way that "breaks" the $u$ constant.
* **Result:** You get a new `u_prime`. When you build the Piezas quartic/elliptic curve for `u_prime`, you are on a **different curve** in the Picard lattice.

### 4. Strategy for Solution #110

1. **Iterate** through your 109 solutions.
2. For each solution, apply the `hutchinson_jump`.
3. Calculate the resulting `new_u`.
4. If `new_u` is not in your current list of $u$-parameters, you have discovered a **new family** of solutions.
5. **Search:** Run your Piezas search (the "walk") on this `new_u`. Even if the jump produced a massive $D$, the elliptic curve walking on that new $u$-fiber might lead you to a much smaller $D$ that you missed.

### 5. Advanced: The 16 Nodes

If the `hutchinson_jump` gives you a point that is too large to work with, try the **"Node Projection"**:
Instead of the cubic map, use a **quadric map** through one of the 16 nodes. On the Piezas $(u, v, w)$ space, this is equivalent to:

Later advice:
The "Dual" Piezas Transformation

$$(u, v, w) mapsto (2-u, 2-v, 2-w)$$

u,v,w
1000/47, -1041/320, -9/20)
>>> 2-u, 2-v, 2-w
(-906/47, 1681/320, 49/20)
>>> verify_uvw(u,v,w)
True
>>> verify_uvw(2-u,2-v,2-w)
False

*(Or similar sign-swaps relative to the constant 2 in your `2(u+v+w) - uvw - 4 = 0` formula).*

By applying these symmetries to your existing $(u, v, w)$ triples, you can generate the 
"translations" mentioned in the papers directly without leaving the Piezas coordinate system.

In Piezas' work, the identity $(u+v+w-2)^2 = uvw$ is a Kummer Surface in disguise. 
(u+v+w-2)**2
2194454025/9048064
>>> u*v*v
5418405/24064

The "2" represents the singular points (nodes).If you apply the map $u mapsto 4/u$ 
or $u mapsto (u-2)/(u+2)$ (depending on your specific normalization), you are essentially 
performing a base-change of the fibration. 

4/u,4/v,4/w
(47/250, -1280/1041, -80/9)
>>> verify_uvw(4/u,4/v,4/w)
False

If you haven't tried searching for $u$ as a square ($u = k^2$), try that—some of the 
most elusive solutions only appear when the elliptic curve $E_u$ gains extra rank through 
a quadratic base change.

Check $u$ is a perfect square, or $2-u$ is a square or 2 k^2
Or $frac{m^2 + n^2}{m^2 - n^2}$.

>>> u.is_square()
False
>>> v.is_square()
False
>>> w.is_square()
False
>>> (2-u).is_square()
False
>>> (2-v).is_square()
False
>>> (2-w).is_square()
False
>>> (4/u).is_square()
False
>>> (4/v).is_square()
False
>>> (4/w).is_square()
False

"""